### ISSUE TITLE
Can't get the app working

### ISSUE THREAD

**Issue by giuseppe-dandrea** [dslul/ticketreader#4]
Hi, I tried the app on the PlayStore on two different phones (Honor 8, Samsung Galaxy s6 edge) with two different tickets (one is the politecnico smart card with the gtt subscription and the other is a 15 rides carnet), but the app doesn't show anything... What's wrong? Thanks

**Comment by dslul** [comment]
Ciao, il programma non supporta le tessere bip (inclusa quella del politecnico), ma il carnet da 15 corse dovrebbe leggerlo. Hai provato ad avvicinarlo senza cover? Qualcuno ha avuto lo stesso problema su galaxy s6 ed era la cover che impediva la lettura.

**Comment by giuseppe-dandrea** [comment]
Si provato sia senza cover, sia a disattivare android Beam. Provando anche con altri lettori di tag nfc, legge qualcosa dalla tessera del poli ma niente dal carnet, infatti mi chiedevo se magari avessero modificato i carnet ultimamente... Mi confermi che funziona con carnet fatti di recente alla macchinetta in metro?

**Comment by dslul** [comment]
Che io sappia non li hanno modificati, è strano che non legga per niente il biglietto...hai provato con nfc tools a vedere se riesci a farglielo leggere?

**Comment by giuseppe-dandrea** [comment]
No il biglietto non è danneggiato, ho provato con un altro carnet fatto al tabacchino (quelli colorati per intenderci) e funziona, perciò è un problema con i biglietti fatti in metro, che a quanto pare non funzionano con l'nfc

**Comment by giuseppe-dandrea** [comment]
Credevo fosse un'altra tipologia, in realta' si era solo smagnetizzato, non ha funzionato neanche in metro, percio' niente, nessun problema, possiamo chiudere l'issue
